//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "abac_access_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub subject_id: i64,
    pub resource_id: i64,
    pub resource_type: String,
    pub action: String,
    pub policy_id: Option<i64>,
    pub decision: String,
    pub request_time: DateTime,
    pub request_ip: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub detail: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
