//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "abac_policy_rule")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub rule_code: String,
    pub rule_name: String,
    pub subject_type: String,
    pub subject_id: Option<i64>,
    pub resource_type: String,
    pub resource_id: Option<i64>,
    pub action: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub condition_json: Option<Json>,
    pub effect: String,
    pub priority: i32,
    pub status: i16,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
    pub deleted: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
