//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "abac_resource_attribute")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub resource_id: i64,
    pub resource_type: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub attr_key_value: Json,
    pub deleted: i16,
    pub create_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
