//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "abac_subject_attribute")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub subject_id: i64,
    pub subject_type: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub attr_key_value: Json,
    pub deleted: i16,
    pub create_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sys_user::Entity",
        from = "Column::SubjectId",
        to = "super::sys_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SysUser,
}

impl Related<super::sys_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SysUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
