//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "aircraft_model")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(unique)]
    pub code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub status: i16,
    pub create_time: DateTime,
    pub update_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::aircraft::Entity")]
    Aircraft,
    #[sea_orm(has_many = "super::model_subject::Entity")]
    ModelSubject,
    #[sea_orm(has_many = "super::pilot_aircraft_model::Entity")]
    PilotAircraftModel,
    #[sea_orm(has_many = "super::pilot_model_flight_time::Entity")]
    PilotModelFlightTime,
}

impl Related<super::aircraft::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Aircraft.def()
    }
}

impl Related<super::model_subject::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModelSubject.def()
    }
}

impl Related<super::pilot_aircraft_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PilotAircraftModel.def()
    }
}

impl Related<super::pilot_model_flight_time::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PilotModelFlightTime.def()
    }
}

impl Related<super::pilot::Entity> for Entity {
    fn to() -> RelationDef {
        super::pilot_aircraft_model::Relation::Pilot.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::pilot_aircraft_model::Relation::AircraftModel
                .def()
                .rev(),
        )
    }
}

impl Related<super::subject::Entity> for Entity {
    fn to() -> RelationDef {
        super::model_subject::Relation::Subject.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::model_subject::Relation::AircraftModel.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
