//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "aircraft_subject_completion")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "aircraft_subject_completion_aircraft_id_subject_id_key")]
    pub aircraft_id: i64,
    #[sea_orm(unique_key = "aircraft_subject_completion_aircraft_id_subject_id_key")]
    pub subject_id: i64,
    pub start_time: Option<DateTime>,
    pub end_time: Option<DateTime>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub flight_hours: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub operation_hours: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub aircraft_running_hours: Option<Decimal>,
    pub completed: bool,
    pub completion_time: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub remark: Option<String>,
    pub create_time: DateTime,
    pub update_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::aircraft::Entity",
        from = "Column::AircraftId",
        to = "super::aircraft::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Aircraft,
    #[sea_orm(
        belongs_to = "super::subject::Entity",
        from = "Column::SubjectId",
        to = "super::subject::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Subject,
}

impl Related<super::aircraft::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Aircraft.def()
    }
}

impl Related<super::subject::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subject.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
