//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "aircraft")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub model_id: i64,
    #[sea_orm(unique)]
    pub plane_no: String,
    pub status: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub remark: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub extra_attrs: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub total_running_hours: Option<Decimal>,
    pub create_time: DateTime,
    pub update_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::aircraft_model::Entity",
        from = "Column::ModelId",
        to = "super::aircraft_model::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AircraftModel,
    #[sea_orm(has_many = "super::aircraft_subject_completion::Entity")]
    AircraftSubjectCompletion,
}

impl Related<super::aircraft_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AircraftModel.def()
    }
}

impl Related<super::aircraft_subject_completion::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AircraftSubjectCompletion.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
