//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "approval_record")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub order_id: i64,
    pub node_order: i32,
    pub approver_id: i64,
    pub approver_name: Option<String>,
    pub action: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub opinion: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub attachment_url: Option<String>,
    pub create_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::approval_order::Entity",
        from = "Column::OrderId",
        to = "super::approval_order::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ApprovalOrder,
}

impl Related<super::approval_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApprovalOrder.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
