//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "approval_order")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub flow_code: String,
    pub biz_id: i64,
    pub biz_type: String,
    pub applicant_id: i64,
    pub applicant_name: Option<String>,
    pub status: String,
    pub current_node_order: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub current_approver_ids: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub attachment_url: Option<String>,
    pub submitted_time: Option<DateTime>,
    pub finished_time: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub remark: Option<String>,
    pub create_time: DateTime,
    pub update_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::approval_record::Entity")]
    ApprovalRecord,
}

impl Related<super::approval_record::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApprovalRecord.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
