//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "approval_node")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub flow_id: i64,
    pub node_order: i32,
    pub node_name: String,
    pub approver_type: String,
    pub approver_value: Option<String>,
    pub approve_strategy: Option<String>,
    pub status: i16,
    pub create_time: DateTime,
    pub update_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::approval_flow::Entity",
        from = "Column::FlowId",
        to = "super::approval_flow::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ApprovalFlow,
}

impl Related<super::approval_flow::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApprovalFlow.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
