//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, TS)]
#[sea_orm(table_name = "flight_sortie")]
#[ts(export,rename = "FlightSortie",rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub plan_id: i64,
    pub sortie_no: String,
    pub aircraft_id: i64,
    pub pilot_id: i64,
    pub commander_id: Option<i64>,
    pub task_type_id: i64,
    pub subject_id: i64,
    pub start_time: DateTime,
    pub end_time: DateTime,
    pub actual_start_time: Option<DateTime>,
    pub actual_end_time: Option<DateTime>,
    pub status: i16,
    pub conflict_flag: i16,
    pub deleted: i16,
    pub create_time: DateTime,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::aircraft::Entity",
        from = "Column::AircraftId",
        to = "super::aircraft::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Aircraft,
    #[sea_orm(
        belongs_to = "super::flight_daily_plan::Entity",
        from = "Column::PlanId",
        to = "super::flight_daily_plan::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FlightDailyPlan,
    #[sea_orm(
        belongs_to = "super::flight_subject::Entity",
        from = "Column::SubjectId",
        to = "super::flight_subject::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FlightSubject,
    #[sea_orm(
        belongs_to = "super::pilot::Entity",
        from = "Column::PilotId",
        to = "super::pilot::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Pilot,
    #[sea_orm(
        belongs_to = "super::sys_user::Entity",
        from = "Column::CommanderId",
        to = "super::sys_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SysUser,
    #[sea_orm(
        belongs_to = "super::task_type::Entity",
        from = "Column::TaskTypeId",
        to = "super::task_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TaskType,
}

impl Related<super::aircraft::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Aircraft.def()
    }
}

impl Related<super::flight_daily_plan::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FlightDailyPlan.def()
    }
}

impl Related<super::flight_subject::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FlightSubject.def()
    }
}

impl Related<super::pilot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pilot.def()
    }
}

impl Related<super::sys_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SysUser.def()
    }
}

impl Related<super::task_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaskType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
