//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, TS)]
#[sea_orm(table_name = "flight_subject")]
#[ts(export,rename = "FlightSubject",rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub subject_name: String,
    pub type_id: i64,
    pub danger_level: i16,
    pub duration: i32,
    pub description: Option<String>,
    pub deleted: i16,
    pub create_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::flight_sortie::Entity")]
    FlightSortie,
    #[sea_orm(
        belongs_to = "super::subject_type::Entity",
        from = "Column::TypeId",
        to = "super::subject_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SubjectType,
}

impl Related<super::flight_sortie::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FlightSortie.def()
    }
}

impl Related<super::subject_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubjectType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
