//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, TS)]
#[sea_orm(table_name = "flight_daily_plan")]
#[ts(export,rename = "FlightDailyPlan",rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub plan_date: Date,
    pub plan_name: String,
    pub status: i16,
    pub creator_id: i64,
    pub deleted: i16,
    pub create_time: DateTime,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::approval_flow::Entity")]
    ApprovalFlow,
    #[sea_orm(has_many = "super::flight_sortie::Entity")]
    FlightSortie,
    #[sea_orm(
        belongs_to = "super::sys_user::Entity",
        from = "Column::CreatorId",
        to = "super::sys_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SysUser,
}

impl Related<super::approval_flow::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApprovalFlow.def()
    }
}

impl Related<super::flight_sortie::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FlightSortie.def()
    }
}

impl Related<super::sys_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SysUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
