//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod abac_access_log;
pub mod abac_policy_rule;
pub mod abac_resource_attribute;
pub mod abac_subject_attribute;
pub mod aircraft;
pub mod aircraft_model;
pub mod aircraft_subject_completion;
pub mod approval_flow;
pub mod approval_node;
pub mod approval_order;
pub mod approval_record;
pub mod model_subject;
pub mod notification;
pub mod pilot;
pub mod pilot_aircraft_model;
pub mod pilot_model_flight_time;
pub mod subject;
pub mod subject_type;
pub mod sys_menu;
pub mod sys_role_menu;
pub mod sys_user;
pub mod task_type;
