//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "model_subject")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub model_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub subject_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::aircraft_model::Entity",
        from = "Column::ModelId",
        to = "super::aircraft_model::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AircraftModel,
    #[sea_orm(
        belongs_to = "super::subject::Entity",
        from = "Column::SubjectId",
        to = "super::subject::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Subject,
}

impl Related<super::aircraft_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AircraftModel.def()
    }
}

impl Related<super::subject::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subject.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
