//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "pilot")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub code: Option<String>,
    pub gender: Option<String>,
    pub age: Option<i32>,
    pub health_status: Option<String>,
    pub mental_status: Option<String>,
    pub level: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub total_flight_hours: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub flight_hours_by_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub break_hours_by_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub remark: Option<String>,
    pub status: i16,
    pub create_time: DateTime,
    pub update_time: DateTime,
    pub user_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::pilot_aircraft_model::Entity")]
    PilotAircraftModel,
    #[sea_orm(has_many = "super::pilot_model_flight_time::Entity")]
    PilotModelFlightTime,
    #[sea_orm(
        belongs_to = "super::sys_user::Entity",
        from = "Column::UserId",
        to = "super::sys_user::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    SysUser,
}

impl Related<super::pilot_aircraft_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PilotAircraftModel.def()
    }
}

impl Related<super::pilot_model_flight_time::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PilotModelFlightTime.def()
    }
}

impl Related<super::sys_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SysUser.def()
    }
}

impl Related<super::aircraft_model::Entity> for Entity {
    fn to() -> RelationDef {
        super::pilot_aircraft_model::Relation::AircraftModel.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::pilot_aircraft_model::Relation::Pilot.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
