//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "pilot_flight_hour")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub pilot_id: i64,
    pub model_id: i64,
    pub total_flight_hours: String,
    pub interrupt_days: i32,
    pub last_flight_date: Option<Date>,
    pub week_year: Option<i32>,
    pub week_no: Option<i32>,
    pub week_flight_hours: String,
    pub month_year: Option<i32>,
    pub month_no: Option<i32>,
    pub month_flight_hours: String,
    pub deleted: i16,
    pub create_time: DateTime,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pilot::Entity",
        from = "Column::PilotId",
        to = "super::pilot::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Pilot,
}

impl Related<super::pilot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pilot.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
