//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::abac_access_log::Entity as AbacAccessLog;
pub use super::abac_policy_rule::Entity as AbacPolicyRule;
pub use super::abac_resource_attribute::Entity as AbacResourceAttribute;
pub use super::abac_subject_attribute::Entity as AbacSubjectAttribute;
pub use super::aircraft::Entity as Aircraft;
pub use super::aircraft_model::Entity as AircraftModel;
pub use super::aircraft_subject_completion::Entity as AircraftSubjectCompletion;
pub use super::approval_flow::Entity as ApprovalFlow;
pub use super::approval_node::Entity as ApprovalNode;
pub use super::approval_order::Entity as ApprovalOrder;
pub use super::approval_record::Entity as ApprovalRecord;
pub use super::model_subject::Entity as ModelSubject;
pub use super::notification::Entity as Notification;
pub use super::pilot::Entity as Pilot;
pub use super::pilot_aircraft_model::Entity as PilotAircraftModel;
pub use super::pilot_model_flight_time::Entity as PilotModelFlightTime;
pub use super::subject::Entity as Subject;
pub use super::subject_type::Entity as SubjectType;
pub use super::sys_menu::Entity as SysMenu;
pub use super::sys_role_menu::Entity as SysRoleMenu;
pub use super::sys_user::Entity as SysUser;
pub use super::task_type::Entity as TaskType;
