//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "subject")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "subject_name_subject_type_key")]
    pub name: String,
    #[sea_orm(unique)]
    pub code: Option<String>,
    pub danger_level: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub default_duration: Decimal,
    #[sea_orm(unique_key = "subject_name_subject_type_key")]
    pub subject_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub status: i16,
    pub create_time: DateTime,
    pub update_time: DateTime,
    pub required_pilots: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::aircraft_subject_completion::Entity")]
    AircraftSubjectCompletion,
    #[sea_orm(has_many = "super::model_subject::Entity")]
    ModelSubject,
}

impl Related<super::aircraft_subject_completion::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AircraftSubjectCompletion.def()
    }
}

impl Related<super::model_subject::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModelSubject.def()
    }
}

impl Related<super::aircraft_model::Entity> for Entity {
    fn to() -> RelationDef {
        super::model_subject::Relation::AircraftModel.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::model_subject::Relation::Subject.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
