//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "sys_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub username: String,
    pub password: String,
    pub real_name: Option<String>,
    pub phone: Option<String>,
    pub email: Option<String>,
    pub status: i16,
    pub deleted: i16,
    pub create_by: Option<i64>,
    pub create_time: DateTime,
    pub update_by: Option<i64>,
    pub update_time: Option<DateTime>,
    pub role: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::abac_subject_attribute::Entity")]
    AbacSubjectAttribute,
    #[sea_orm(has_many = "super::pilot::Entity")]
    Pilot,
}

impl Related<super::abac_subject_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AbacSubjectAttribute.def()
    }
}

impl Related<super::pilot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pilot.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
